name: my_dashatar_app
description: The Dashatar App is a foundational Flutter application introduced in the "Complete Flutter Course" by Coding Liquids. This module provides learners with a step-by-step guide to creating a basic yet functional Flutter app, emphasizing core concepts and best practices.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/dash.png"
  adaptive_icon_background: "#000000"

  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/
